CREATE TABLE `flight_history` (
	`id` int AUTO_INCREMENT NOT NULL,
	`flightIata` varchar(16) NOT NULL,
	`flightIcao` varchar(16),
	`airlineName` varchar(128),
	`airlineIata` varchar(8),
	`aircraft` varchar(64),
	`regNumber` varchar(16),
	`depIata` varchar(8),
	`depCity` varchar(64),
	`arrIata` varchar(8),
	`arrCity` varchar(64),
	`scheduledDepUtc` varchar(32),
	`actualDepUtc` varchar(32),
	`scheduledArrUtc` varchar(32),
	`actualArrUtc` varchar(32),
	`scheduledDepLocal` varchar(32),
	`actualDepLocal` varchar(32),
	`scheduledArrLocal` varchar(32),
	`actualArrLocal` varchar(32),
	`depDelayMin` int,
	`arrDelayMin` int,
	`durationMin` int,
	`actualDurationMin` int,
	`distanceKm` int,
	`baggageBelt` varchar(16),
	`arrTerminal` varchar(16),
	`arrGate` varchar(16),
	`runwayLanded` varchar(16),
	`prayerCount` int DEFAULT 0,
	`prayerNames` text,
	`prayerDetails` text,
	`trackedAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `flight_history_id` PRIMARY KEY(`id`)
);
